name: buqui_burgers
description: Buqui Burgers
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: 0.13.1
  intl: ^0.19.0
  flutter_layout_grid: 2.0.5
  flutter_rating_bar: 4.0.1
  go_router: ^13.1.0
  rxdart: 0.27.7
  path_provider: ^2.1.2
  http: ^1.2.1
  json_annotation: ^4.8.1
  build_runner: ^2.4.8
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: 3.0.1
  mocktail: ^1.0.3
  json_serializable: ^6.7.1

flutter_icons:
  # Custom app icon. For more info see: https://pub.dev/packages/flutter_launcher_icons
  ios: true
  android: false

flutter:
  uses-material-design: true

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
