// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjxJdcPYIF5CsXBJOuxDKvNavxDTm3N44',
    appId: '1:45782405987:web:e0ea07bc5d786b0f26f956',
    messagingSenderId: '45782405987',
    projectId: 'anya-7258c',
    authDomain: 'anya-7258c.firebaseapp.com',
    storageBucket: 'anya-7258c.appspot.com',
    measurementId: 'G-9T4MGTPG9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsNAsJkgUVdo0C5oTH1mbW1f4CYo081e8',
    appId: '1:45782405987:android:6efcf670f6d2044a26f956',
    messagingSenderId: '45782405987',
    projectId: 'anya-7258c',
    storageBucket: 'anya-7258c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4wAPOkL3zXHi_Ce-znL6XPp5bBTi8VLA',
    appId: '1:45782405987:ios:aaa815427289d4b226f956',
    messagingSenderId: '45782405987',
    projectId: 'anya-7258c',
    storageBucket: 'anya-7258c.appspot.com',
    iosBundleId: 'com.example.session2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4wAPOkL3zXHi_Ce-znL6XPp5bBTi8VLA',
    appId: '1:45782405987:ios:798f13d996c01b9226f956',
    messagingSenderId: '45782405987',
    projectId: 'anya-7258c',
    storageBucket: 'anya-7258c.appspot.com',
    iosBundleId: 'com.example.session2.RunnerTests',
  );
}
